name: mmmg
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - paddleocr==2.10.0
      - paddlepaddle-gpu==2.6.2
      - openai==1.82.0
      - azure-identity
      - datasets
      - networkx==3.4.2
      - scikit-learn
      - matplotlib
      - tqdm
      - -e ./mmmg-eval/sam2
